server:
  port: 9527


spring:
  application:
    name: cloud-geteway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态路由，利用微服务名进行路由
      routes:
        - id: payment_routh  #路由的ID，没有固定规则，要求唯一
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址
          predicates:          #断言：路径相匹配的进行路由
            - Path=/payment/get/**
        - id: payment_routh2
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
              - Path=/payment/lb/**
              - After=2021-10-02T15:10:46.030+08:00[Asia/Shanghai]
#              - Cookie=username,ll




eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true