spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/java?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

---
server:
  port: 8082
spring:
  profiles: pro

dog:
  name: xx
  age: 12
  address: 北京
  birth: 2021/4/9