spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java
    username: root
    password: 123456
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      filters: stat,wall
      aop-patterns: com.shijl.*    #监控bean

      stat-view-servlet:       #开启监控
        enabled: true
        login-username: admin  #监控页登录用户名
        login-password: 123    #登录密码
        reset-enable: false   #监控页面的重置按钮

      web-stat-filter:   #web监控
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*

      filter:
        stat:
          slow-sql-millis: 1000   #统计慢查询
          log-slow-sql: true     #日志是否记录慢查询
          enabled: true
        wall:   #防火墙
          enabled: true
          config:
            drop-table-allow: false
  #            update-allow:  false

  jdbc:
    template:
#   查询超时时间   秒
      query-timeout: 3

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


#mybatis配置
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml   #  mybatis全局配置文件
  mapper-locations: classpath:mapper/*.xml        #SQL映射文件位置
  configuration:   #指定mybatis全局配置
    map-underscore-to-camel-case: true    #开启驼峰命名
#可以不写mybatis全局配置文件，所有的全局配置都写在configuration下

#server:
#  port: 8080

